version: '3.7'
volumes:
  pg-data:

services:
  db:
    image: "postgres:12.4"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
  telebot:
    build: .
    command: ["python", "run.py"]
    volumes:
      - .:/code