"""rm: emails

Revision ID: 3d94dcfd9fba
Revises: 9a74454b0a38
Create Date: 2021-10-03 17:12:12.196579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d94dcfd9fba'
down_revision = '9a74454b0a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=50), nullable=True))
    op.drop_column('students', 'emails')
    op.add_column('teachers', sa.Column('email', sa.String(length=50), nullable=True))
    op.drop_column('teachers', 'emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('emails', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'email')
    op.add_column('students', sa.Column('emails', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
