"""add: works subject_id and group_id

Revision ID: 56c24ff4140d
Revises: e87033798866
Create Date: 2021-10-04 15:34:21.340088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c24ff4140d'
down_revision = 'e87033798866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('group_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'group_id')
    # ### end Alembic commands ###
