"""fix: string len

Revision ID: 60633b4e09be
Revises: dd6545167c42
Create Date: 2021-10-08 17:01:22.376043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60633b4e09be'
down_revision = 'dd6545167c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
