"""add new tabels

Revision ID: 796c2d42a776
Revises: b0349f829a6e
Create Date: 2021-10-03 11:42:12.795848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796c2d42a776'
down_revision = 'b0349f829a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('exams', 'student_id')
    op.add_column('groups', sa.Column('faulty_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('emails', sa.JSON(), server_default='[]', nullable=False))
    op.drop_column('students', 'email')
    op.add_column('teachers', sa.Column('emails', sa.JSON(), server_default='[]', nullable=False))
    op.drop_column('teachers', 'email')
    op.add_column('universities', sa.Column('city_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'city_id')
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'emails')
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('students', 'emails')
    op.drop_column('groups', 'faulty_id')
    op.add_column('exams', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('grades')
    op.drop_table('faculties')
    op.drop_table('cities')
    # ### end Alembic commands ###
