"""add: discipline for works

Revision ID: 964495c81da4
Revises: 032ebf4e981f
Create Date: 2021-11-18 15:05:26.390063

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from assessment_src.models import DisciplineEnum

revision = '964495c81da4'
down_revision = '032ebf4e981f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('discipline', sqlalchemy_utils.types.choice.ChoiceType(DisciplineEnum, impl=sa.Integer())))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'discipline')
    # ### end Alembic commands ###
