"""fix struct

Revision ID: 9829542e6ee7
Revises: 964495c81da4
Create Date: 2021-12-03 21:57:32.228630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9829542e6ee7'
down_revision = '964495c81da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subjects_group_id', table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('groups')
    op.drop_column('students', 'group_id')
    op.drop_column('students', 'time_start')
    op.drop_column('teachers', 'group_id')
    op.drop_column('teachers', 'time_start')
    op.alter_column('works', 'discipline',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_works_group_id', table_name='works')
    op.drop_index('ix_works_subject_id', table_name='works')
    op.drop_index('ix_works_teacher_id', table_name='works')
    op.drop_column('works', 'subject_id')
    op.drop_column('works', 'teacher_id')
    op.drop_column('works', 'group_id')
    op.drop_column('works', 'time_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('works', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('works', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('works', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_works_teacher_id', 'works', ['teacher_id'], unique=False)
    op.create_index('ix_works_subject_id', 'works', ['subject_id'], unique=False)
    op.create_index('ix_works_group_id', 'works', ['group_id'], unique=False)
    op.alter_column('works', 'discipline',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('teachers', sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey')
    )
    op.create_index('ix_subjects_group_id', 'subjects', ['group_id'], unique=False)
    # ### end Alembic commands ###
