"""add: index

Revision ID: 990872584df4
Revises: f901f5ce338a
Create Date: 2021-10-04 17:29:41.800529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990872584df4'
down_revision = 'f901f5ce338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_index(op.f('ix_grades_work_id'), 'grades', ['work_id'], unique=False)
    op.alter_column('works', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('works', 'token',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_works_admin_id'), 'works', ['admin_id'], unique=False)
    op.create_index(op.f('ix_works_group_id'), 'works', ['group_id'], unique=False)
    op.create_index(op.f('ix_works_subject_id'), 'works', ['subject_id'], unique=False)
    op.create_index(op.f('ix_works_teacher_id'), 'works', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_works_token'), 'works', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_token'), table_name='works')
    op.drop_index(op.f('ix_works_teacher_id'), table_name='works')
    op.drop_index(op.f('ix_works_subject_id'), table_name='works')
    op.drop_index(op.f('ix_works_group_id'), table_name='works')
    op.drop_index(op.f('ix_works_admin_id'), table_name='works')
    op.alter_column('works', 'token',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('works', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_grades_work_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    # ### end Alembic commands ###
