"""fix: tabels

Revision ID: 9a74454b0a38
Revises: 796c2d42a776
Create Date: 2021-10-03 17:09:48.907443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a74454b0a38'
down_revision = '796c2d42a776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.drop_column('groups', 'university_id')
    op.drop_column('groups', 'faulty_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('faulty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('groups', 'faculty_id')
    op.drop_column('exams', 'admin_id')
    # ### end Alembic commands ###
