"""add: eail for student and teacher

Revision ID: b0349f829a6e
Revises: b694660a0473
Create Date: 2021-10-02 14:18:44.214305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0349f829a6e'
down_revision = 'b694660a0473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=30), nullable=True))
    op.add_column('teachers', sa.Column('email', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'email')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
