"""rm: email

Revision ID: dd6545167c42
Revises: fd5726354aa1
Create Date: 2021-10-07 19:41:44.382630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6545167c42'
down_revision = 'fd5726354aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    op.drop_column('teachers', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
