"""fix: stuct tables and add subject

Revision ID: e87033798866
Revises: 3d94dcfd9fba
Create Date: 2021-10-04 11:30:44.910558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e87033798866'
down_revision = '3d94dcfd9fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exams')
    op.add_column('grades', sa.Column('work_id', sa.Integer(), nullable=False))
    op.drop_column('grades', 'exam_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('grades', 'work_id')
    op.create_table('exams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='exams_pkey')
    )
    op.drop_table('works')
    op.drop_table('subjects')
    # ### end Alembic commands ###
