"""rm: teacher_id for grade

Revision ID: f901f5ce338a
Revises: 56c24ff4140d
Create Date: 2021-10-04 16:34:13.492220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f901f5ce338a'
down_revision = '56c24ff4140d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
