"""add: group_id for subjects

Revision ID: fd5726354aa1
Revises: 990872584df4
Create Date: 2021-10-05 10:49:53.152942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5726354aa1'
down_revision = '990872584df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_subjects_group_id'), 'subjects', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_group_id'), table_name='subjects')
    op.drop_column('subjects', 'group_id')
    # ### end Alembic commands ###
